#!/usr/bin/env python
# coding: utf-8

# # Assignment-1

# In[6]:


str1="what we think we become; we are python programmers,How it is and what it is"
str1.find("we")


# In[7]:


str1.rfind("we")


# In[8]:


str1.count("we")


# In[9]:


str1.find("what")


# In[10]:


str1.rfind("what")


# In[11]:


str1.count("what")


# In[12]:


str1.index("we")


# In[13]:


print(str1)


# # Assignment-2

# In[14]:


str1="python"
str2="programmer"
str3="letsupgrade"
str4="batchsix"
str1.upper()


#  UPPER FUNCTIONS

# In[15]:


str5=str2.upper()
print(str5)


# In[16]:


str3.upper()


# In[17]:


str4.upper()


# In[18]:


str1.islower()


# In[19]:


str1="PYTHON"
str2="PROGRAMMER"
str3="LETSUPGRADE"
str4="BATCHSIX"
str1.lower()


# LOWER FUNCTIONS

# In[20]:


str2.lower()


# In[21]:


str3.lower()


# In[22]:


str4.lower()


# In[23]:


str1.isupper()
