#!/usr/bin/env python
# coding: utf-8

# # Assignment 1

# In[10]:


num = int(input("Enter a +ve value:"))
sum = 0
while(num > 0):
    sum += num
    num = num - 1
print("The sum is", sum)


# # Assignment 2

# In[17]:


number = int(input("Enter a value:"))
if number > 1:
    for i in range(2, number):
        if (number % i) == 0:
            print(number, "is not a prime number")
            break
    else:
        print(number, "is a prime number")

else:
    print(number, "is not a prime number")
